<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5cbfc9a5-4785-41fa-a137-7c2e7a7a9380</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="src\**" />
    <Compile Remove="tests\**" />
    <Content Remove="src\**" />
    <Content Remove="tests\**" />
    <EmbeddedResource Remove="src\**" />
    <EmbeddedResource Remove="tests\**" />
    <None Remove="src\**" />
    <None Remove="tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="src/VCS.CoreV3.Infrastructure/VCS.CoreV3.Infrastructure.csproj" />
  </ItemGroup>

</Project>
